import { createElement, type ReactElement } from 'react'

/**
 * ServerStyleSheet — collects component CSS during server-side rendering.
 *
 * Usage:
 *   const sheet = new ServerStyleSheet()
 *   // Pass sheet.collect to your render pipeline
 *   // Then call sheet.getStyleTags() or sheet.getStyleElement()
 *   sheet.seal()
 */
export class ServerStyleSheet {
  private styles = new Map<string, string>()
  private sealed = false

  /** Collect a CSS chunk identified by a unique id. Ignored after seal(). */
  collect(id: string, css: string): void {
    if (this.sealed) return
    this.styles.set(id, css)
  }

  /** Return all collected styles as `<style>` tag HTML strings. */
  getStyleTags(): string {
    return Array.from(this.styles.entries())
      .map(([id, css]) => `<style data-ui-style="${id}">${css}</style>`)
      .join('\n')
  }

  /**
   * Return a single React `<style>` element containing all collected CSS.
   * The CSS is library-generated (not user input) so innerHTML is safe here.
   */
  getStyleElement(): ReactElement {
    const css = Array.from(this.styles.values()).join('\n')
    return createElement('style', {
      'data-ui-styles': 'ssr',
      // Safe: CSS is generated by the library, not from user input
      dangerouslySetInnerHTML: { __html: css },
    })
  }

  /** Return all collected CSS as a single string. */
  getCSS(): string {
    return Array.from(this.styles.values()).join('\n')
  }

  /** Prevent further collection. Call after rendering is complete. */
  seal(): void {
    this.sealed = true
  }

  /** Number of unique style chunks collected. */
  get size(): number {
    return this.styles.size
  }
}
