// Core engines
export * from './core/styles'
// Motion — re-export everything except Timeline (name conflict with component)
export { solveSpring, springToLinearEasing, springDuration } from './core/motion/spring'
export type { SpringConfig } from './core/motion/spring'
export { animate, spring } from './core/motion/animate'
export type { AnimateOptions, AnimationResult } from './core/motion/animate'
export { solveDecay, solveGravity } from './core/motion/physics'
export type { DecayConfig } from './core/motion/physics'
export { Timeline as AnimationTimeline, timeline } from './core/motion/timeline'
export { computeStaggerDelays } from './core/motion/stagger'
export type { StaggerConfig, StaggerFrom } from './core/motion/stagger'
export { useScrollReveal, supportsScrollDrivenAnimations } from './core/motion/scroll'
export type { ScrollRevealOptions } from './core/motion/scroll'
export { flip } from './core/motion/flip'
export { TextSplitter } from './core/motion/text-splitter'
export type { TextSplitterProps } from './core/motion/text-splitter'
export { interpolatePath } from './core/motion/morph'
export { motion } from './core/motion/controller'
export { MotionContext, MotionProvider } from './core/motion/motion-context'
export { useMotionLevel } from './core/motion/use-motion-level'
export { useEntrance } from './core/motion/use-entrance'
export type { EntranceAnimation } from './core/motion/use-entrance'
export { useSkeletonTransition } from './core/motion/use-skeleton-transition'
export type { SkeletonTransitionResult } from './core/motion/use-skeleton-transition'
export { useScrollScene } from './core/motion/scroll-scene'
export type { ScrollSceneConfig } from './core/motion/scroll-scene'
export * from './core/tokens'
export * from './core/icons'
export * from './core/a11y'
export * from './core/input'
export * from './core/utils'
export * from './core/forms'

// Components
export * from './components'

// Domain
export * from './domain'
